### ISSUE TITLE
Jarvis throws an error with CTest

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hermes#692]
Jarvis throws an error when CTest is running:

```
Traceback (most recent call last):
  File "/home/runner/.local/bin/jarvis", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/runner/work/actions/actions/jarvis-cd/bin/jarvis", line 1515, in <module>
    args.process_args()
  File "/home/runner/.local/lib/python3.10/site-packages/jarvis_util/util/argparse.py", line 132, in process_args
    func()
  File "/home/runner/work/actions/actions/jarvis-cd/bin/jarvis", line 1275, in pipeline_run_yaml
    pipeline = Pipeline().from_yaml(path).save()
  File "/home/runner/work/actions/actions/jarvis-cd/jarvis_cd/basic/pkg.py", line 1012, in from_yaml
    return self.from_yaml_dict(config, do_configure)
  File "/home/runner/work/actions/actions/jarvis-cd/jarvis_cd/basic/pkg.py", line 990, in from_yaml_dict
    self.copy_static_env(config['env'])
  File "/home/runner/work/actions/actions/jarvis-cd/jarvis_cd/basic/pkg.py", line 1067, in copy_static_env
    static_env_path = self.get_static_env_path(env_name)
  File "/home/runner/work/actions/actions/jarvis-cd/jarvis_cd/basic/pkg.py", line 1056, in get_static_env_path
    return os.path.join(self.jarvis.env_dir, f'{env_name}.yaml')
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
```

I'm not sure whether it's Jarvis issue or CTest script setting issue.

From: https://my.cdash.org/viewTest.php?onlyfailed&buildid=2664243

**Comment by hyoklee** [comment]
jarvis init solved the problem.
```
# Initialize the Jarvis testing Hermes environment
jarvis init \
"${HOME}/jarvis-config" \
"${HOME}/jarvis-priv" \
"${HOME}/jarvis-shared"
cp /hermes/ci/resource_graph.yaml /jarvis-cd/config/resource_graph.yaml
jarvis env build hermes
```
